/// Autogenerated from uploaded google-services JSON (Android values).
/// WARNING: this file contains API key and project identifiers. Do NOT publish secrets publicly.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return FirebaseOptions(
        apiKey: 'AIzaSyA53L4EUt12j02qpoRzeI7LY0Cw82rUoCI',
        appId: '1:1014917927583:android:79906b34e6c742aa2288aa',
        messagingSenderId: '1014917927583',
        projectId: 'pharmaqms-v2',
        storageBucket: 'pharmaqms-v2.firebasestorage.app',
      );
    }
    // Web, iOS and other platforms are not configured in this autogenerated file.
    return null;
  }
}
