name: pharma_qms_user
description: Pharma QMS - User app (with Firebase scaffolding)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_html: ^3.0.0
  provider: ^6.0.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3

flutter:
  uses-material-design: true
